services:
  - type: web
    name: consultations
    runtime: python
    repo: https://github.com/rdbwk7z84d-ship-it/consultations
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8510661599:AAHS65zDE4p-8A2CX1N9t-7h0p8Ix4MgW3Y
      - key: BLOGGER_ID
        value: 8695107966
      - key: ADMIN_CHANNEL_ID
        value: -1004321519689
